const fs = require('fs');
const path = require('path');

const DIST_DIR = path.join(__dirname, '../dist');
const PUBLIC_DIR = path.join(__dirname, '../public');

console.log('[strip_js_fallback] Running post-build KaiOS production optimizer...');

if (!fs.existsSync(DIST_DIR)) {
  console.error('[strip_js_fallback] dist directory does not exist! Run build first.');
  process.exit(1);
}

// 1. Ensure whot_engine_asm.js is in dist if present in public
const srcAsm = path.join(PUBLIC_DIR, 'whot_engine_asm.js');
const destAsm = path.join(DIST_DIR, 'whot_engine_asm.js');
if (fs.existsSync(srcAsm)) {
  fs.copyFileSync(srcAsm, destAsm);
  console.log('[strip_js_fallback] Copied compiled Emscripten whot_engine_asm.js to dist/');
} else {
  console.log('[strip_js_fallback] Note: whot_engine_asm.js will be generated by GitHub Actions Emscripten workflow.');
}

// 2. Inject Emscripten-first bootstrap configuration into dist/index.html
const indexHtmlPath = path.join(DIST_DIR, 'index.html');
if (fs.existsSync(indexHtmlPath)) {
  let html = fs.readFileSync(indexHtmlPath, 'utf8');
  
  // Inject script to load whot_engine_asm.js if available before app initializes
  const emscriptenBootstrap = `
  <script>
    window.WHOT_PROD_MODE = true;
    window.WHOT_EMSCRIPTEN_REQUIRED = true;
  </script>
  <script src="whot_engine_asm.js" onerror="console.warn('asm.js loading notice: running in web preview')"></script>
  `;

  if (!html.includes('WHOT_EMSCRIPTEN_REQUIRED')) {
    html = html.replace('<head>', '<head>' + emscriptenBootstrap);
    fs.writeFileSync(indexHtmlPath, html, 'utf8');
    console.log('[strip_js_fallback] Injected Emscripten asm.js production loader into dist/index.html');
  }
}

console.log('[strip_js_fallback] Production optimization complete.');
